import { docs } from 'collections/server';
import { loader } from 'fumadocs-core/source';
import { createOpenAPI } from 'fumadocs-openapi/server';
import type { ReactNode } from 'react';
import { docsContentRoute, docsImageRoute, docsRoute } from './shared';

// Reads apps/site/public/openapi.json (generated by
// apps/api/internal/handler/apidoc_generate_test.go, see task
// generate:api-docs) — content/docs/api/*.mdx's own `_openapi.preload`
// frontmatter (written by generate-api-pages.mjs) names this same path.
export const openapi = createOpenAPI({
  input: ['./public/openapi.json'],
});

// See https://fumadocs.dev/docs/headless/source-api for more info
export const source = loader({
  baseUrl: docsRoute,
  source: docs.toFumadocsSource(),
  plugins: [openapi.loaderPlugin()],
});

type PageTreeRoot = ReturnType<typeof source.getPageTree>;
type PageTreeNode = PageTreeRoot['children'][number];

// AdminOnlyBadge marks a sidebar entry — item, folder, or (post-flatten)
// separator — whose operation(s) all require the Admin role, derived from
// each page's own `admin` frontmatter (written by
// apps/site/scripts/generate-api-pages.mjs's markAdminOperations off the
// spec's `security` block; see source.config.ts for why the flag has to be
// declared on pageSchema too, or Zod silently drops it). Styled off the same
// fd-* CSS variables layout.tsx's TabIcon already uses, so it reads as part
// of the same design language rather than a one-off.
function AdminOnlyBadge() {
  return (
    <span className="border-fd-border bg-fd-muted text-fd-muted-foreground shrink-0 rounded-full border px-1.5 py-0.5 text-[10px] leading-none font-medium">
      Admin only
    </span>
  );
}

// decorate adds the badge when `admin` is true; otherwise returns `name`
// untouched. No prefix-stripping here — apps/site/api-domains.json gives
// every admin domain a `title` that already carries no "(Admin)" qualifier
// (the tag itself keeps it, since openapi.json has no concept of a badge —
// see the file-level comment on DOMAINS in generate-api-pages.mjs), so the
// name arriving here is already clean. An earlier version of this function
// stripped an "Admin — " prefix at render time because tag and sidebar
// title were still the same string doing two jobs; splitting them into
// separate fields made that stripping dead code.
function decorate(name: ReactNode, admin: boolean): ReactNode {
  if (!admin) return name;
  return (
    // key: found live, not predicted — fumadocs-ui's sidebar button/
    // separator renderers pass their `name` prop straight into a list of
    // children React itself keys (icon, name, trailing content), so a
    // plain string `name` never needed one but this multi-child
    // replacement does. A shared constant is fine — key uniqueness is only
    // required among the siblings in ONE such list, and each rendered name
    // is the only badge-bearing span in its own.
    <span key="admin-only-name" className="inline-flex items-center gap-1.5">
      {name}
      <AdminOnlyBadge />
    </span>
  );
}

// allAdmin reports whether every operation page reachable under `node` is
// admin-gated — a Folder with no reachable pages is NOT vacuously true (an
// empty section badged "Admin only" would be actively wrong), and a bare
// Separator (no children to inspect) never is either. This is the single
// derivation FOLDER/SEPARATOR badging uses — "every child is admin" is
// computed structurally, not tracked as a second, separately-set flag that
// could drift from what the items actually say.
function allAdmin(node: PageTreeNode, adminUrls: Set<string>): boolean {
  if (node.type === 'page') return adminUrls.has(node.url);
  if (node.type === 'separator') return false;
  const leaves = node.index ? [node.index, ...node.children] : node.children;
  return leaves.length > 0 && leaves.every((child) => allAdmin(child, adminUrls));
}

// decorateChildren applies item-level badges to `children`, but ONLY when
// `containerAllAdmin` is false — when the immediate container (the folder
// these children sit directly under) is itself getting a folder-level
// badge, badging every child too would be redundant clutter for no extra
// signal (see the 6 item-badge cases living in otherwise-mixed sections
// like Logs & Request Traces, vs. the ~40 operations under Admin — Platform
// that get exactly one badge, on the section, not one each). A child that
// is itself a folder (only "git"'s two children today) is decorated with
// its OWN freshly computed badge, recursing independently — a section can
// be mixed overall while one of its own sub-folders is fully admin, or vice
// versa, and each level's badge has to reflect only that level's children.
function decorateChildren(children: PageTreeNode[], containerAllAdmin: boolean, adminUrls: Set<string>): PageTreeNode[] {
  return children.map((child) => {
    if (child.type === 'folder') {
      const badge = allAdmin(child, adminUrls);
      return { ...child, name: decorate(child.name, badge), children: decorateChildren(child.children, badge, adminUrls) };
    }
    if (child.type === 'page' && !containerAllAdmin && adminUrls.has(child.url)) {
      return { ...child, name: decorate(child.name, true) };
    }
    return child;
  });
}

// Render each SECTION folder (Server, Project, Application, Database under Core;
// live-updates, account, git, … under API) as a non-collapsible separator
// group — like the "Overview" group — instead of a collapsible folder. Only
// the sidebar tree changes: the pages keep their own nested URLs
// (`/docs/core/server/git`, …), so routing is unaffected. Doubly-nested
// folders (e.g. Application → Frameworks, or API's git → integrations/
// providers) stay collapsible — this only flattens one level.
//
// adminUrls badging rides along here rather than as a separate pass: badge
// status has to be computed BEFORE a folder collapses into a separator (a
// bare Separator has no `.children` left to inspect), so it has to happen
// at the same point flattening decides a node is a section in the first
// place.
function flattenSections(nodes: PageTreeNode[], adminUrls: Set<string>): PageTreeNode[] {
  const out: PageTreeNode[] = [];
  for (const node of nodes) {
    if (node.type === 'folder') {
      const badge = allAdmin(node, adminUrls);
      out.push({ type: 'separator', name: decorate(node.name, badge) });
      if (node.index) out.push(...decorateChildren([node.index], badge, adminUrls));
      out.push(...decorateChildren(node.children, badge, adminUrls));
    } else {
      out.push(node);
    }
  }
  return out;
}

// Two `root: true` folders (Core, API — meta.json's "root" flag) exist so
// DocsLayout can render them as sidebar tabs (see `tabs` in layout.tsx): a
// root folder must stay a folder node, intact, for `getLayoutTabs()` to find
// it and for DocsLayout to scope the sidebar to whichever one is active. The
// flattening above therefore can't run at the top level like it used to when
// there was only one section total — it has to run INSIDE each root's own
// children instead, so "Server"/"Project"/etc. still render as flat groups
// once you're inside the Core tab, rather than as a nested collapsible folder.
export function getSidebarTree(): PageTreeRoot {
  const tree = source.getPageTree();
  const children: PageTreeNode[] = [];

  // Page tree nodes carry no `security` field — building this set from
  // source.getPages() (public API, not the tree's own @internal $ref) is
  // the one place admin status is read off page data, then threaded through
  // flattenSections/decorateChildren by URL rather than re-derived per node.
  const adminUrls = new Set(source.getPages().filter((page) => page.data.admin).map((page) => page.url));

  for (const node of tree.children) {
    if (node.type === 'folder' && node.root) {
      children.push({ ...node, children: flattenSections(node.children, adminUrls) });
    } else if (node.type === 'folder') {
      children.push(...flattenSections([node], adminUrls));
    } else {
      children.push(node);
    }
  }

  return { ...tree, children };
}

export function getPageImage(page: (typeof source)['$inferPage']) {
  const segments = [...page.slugs, 'image.png'];

  return {
    segments,
    url: `${docsImageRoute}/${segments.join('/')}`,
  };
}

export function getPageMarkdownUrl(page: (typeof source)['$inferPage']) {
  const segments = [...page.slugs, 'content.md'];

  return {
    segments,
    url: `${docsContentRoute}/${segments.join('/')}`,
  };
}

export async function getLLMText(page: (typeof source)['$inferPage']) {
  const processed = await page.data.getText('processed');

  return `# ${page.data.title} (${page.url})

${processed}`;
}
