import { readFileSync } from 'node:fs';
import { docs } from 'collections/server';
import { loader } from 'fumadocs-core/source';
import { createOpenAPI } from 'fumadocs-openapi/server';
import type { Document } from 'fumadocs-openapi';
import type { ReactNode } from 'react';
import { docsContentRoute, docsImageRoute, docsRoute } from './shared';

// apps/site/public/openapi.json, generated by
// apps/api/internal/handler/apidoc_generate_test.go (task generate:api-docs).
// The key MUST stay this exact string: content/docs/api/*.mdx embed it as
// `<Comp document="./public/openapi.json">` and `_openapi.preload`, and
// createOpenAPI resolves that key against `resolvedInput`.
const SPEC_PATH = './public/openapi.json';

// What the SITE renders is not byte-identical to public/openapi.json on disk.
// The file is the complete, authoritative, machine-readable artifact —
// third-party codegen consumes it directly and it correctly states that a
// dashboard session authenticates every route, alongside the PAT scope. What
// follows strips the "or a session" alternative from each operation IN
// MEMORY only, for one reason: this reference's audience scripts with a
// personal access token, /api/auth/login isn't in the spec at all, so a
// `session` entry in a rendered Authorization panel is a second credential
// field the reader can't act on. This same in-memory spec also feeds the
// search index and the llms.txt / llms-full.txt routes (they read it through
// `source` below), so `session` drops out of those too — a deliberate
// consequence for the same audience, not an accident.
//
// The guard: an empty `security: []` in OpenAPI is an affirmative "this
// operation needs NO authentication" and overrides global security — it is
// not "unspecified". The 35 session-only operations carry security exactly
// `[{ session: [] }]`; filtering `session` unconditionally would empty those
// and declare the WS terminal tunnel, token minting, and every delete/reveal
// endpoint public. Nothing renders a page for them, which is exactly what
// would let it slip by — but the path-walking surfaces above would inherit
// the claim. So `session` is removed only when a scope alternative survives;
// a session-only operation keeps `[{ session: [] }]`, which is true and inert.
const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'] as const;
const spec = JSON.parse(readFileSync(SPEC_PATH, 'utf8')) as Document;
for (const [path, pathItem] of Object.entries(spec.paths ?? {})) {
  if (!pathItem) continue;
  for (const method of HTTP_METHODS) {
    const operation = pathItem[method];
    if (!operation || !Array.isArray(operation.security)) continue;
    const kept = operation.security.filter((requirement) => !('session' in requirement));
    if (kept.length > 0) operation.security = kept;
    if (operation.security.length === 0) {
      throw new Error(`source.tsx: stripping \`session\` left ${method.toUpperCase()} ${path} with an empty security array — it would render as requiring no authentication`);
    }
  }
}

export const openapi = createOpenAPI({
  input: { [SPEC_PATH]: spec },
});

// See https://fumadocs.dev/docs/headless/source-api for more info
export const source = loader({
  baseUrl: docsRoute,
  source: docs.toFumadocsSource(),
  plugins: [openapi.loaderPlugin()],
});

type PageTreeRoot = ReturnType<typeof source.getPageTree>;
type PageTreeNode = PageTreeRoot['children'][number];

// roleBadgeLabel renders a role set as the badge text — ["admin"] ->
// "Admin only", ["admin","owner"] -> "Admin or Owner only". Derived from the
// role names (which come from routes.go via x-belune-roles), so a role
// rename flows through with nothing here to update. The set arrives sorted
// from the Go side, so the label is stable.
function roleBadgeLabel(roles: string[]): string {
  return roles.map((r) => r[0].toUpperCase() + r.slice(1)).join(' or ') + ' only';
}

// RoleBadge marks a sidebar entry — item, folder, or (post-flatten)
// separator — whose operation(s) all require the same role set, derived from
// each page's own `roles` frontmatter (written by
// apps/site/scripts/generate-api-pages.mjs's markAdminOperations off the
// spec's x-belune-roles; see source.config.ts for why the key has to be
// declared on pageSchema too, or Zod silently drops it). Styled off the same
// fd-* CSS variables layout.tsx's TabIcon already uses, so it reads as part
// of the same design language rather than a one-off.
function RoleBadge({ label }: { label: string }) {
  return (
    <span className="border-fd-border bg-fd-muted text-fd-muted-foreground shrink-0 rounded-full border px-1.5 py-0.5 text-[10px] leading-none font-medium">
      {label}
    </span>
  );
}

// decorate adds the badge when `roles` is a non-empty set; otherwise returns
// `name` untouched. No prefix-stripping here — apps/site/api-domains.json
// gives every role-gated domain a `title` that already carries no "(Admin)"
// qualifier (the tag itself keeps it, since openapi.json has no concept of a
// badge — see the file-level comment on DOMAINS in generate-api-pages.mjs),
// so the name arriving here is already clean. An earlier version of this
// function stripped an "Admin — " prefix at render time because tag and
// sidebar title were still the same string doing two jobs; splitting them
// into separate fields made that stripping dead code.
function decorate(name: ReactNode, roles: string[] | null): ReactNode {
  if (!roles || roles.length === 0) return name;
  return (
    // key: found live, not predicted — fumadocs-ui's sidebar button/
    // separator renderers pass their `name` prop straight into a list of
    // children React itself keys (icon, name, trailing content), so a
    // plain string `name` never needed one but this multi-child
    // replacement does. A shared constant is fine — key uniqueness is only
    // required among the siblings in ONE such list, and each rendered name
    // is the only badge-bearing span in its own.
    <span key="role-badge-name" className="inline-flex items-center gap-1.5">
      {name}
      <RoleBadge label={roleBadgeLabel(roles)} />
    </span>
  );
}

// rolesKey is a canonical string for a role set, for equality checks. The
// set arrives sorted from Go, so JSON.stringify is a stable key.
function rolesKey(roles: string[]): string {
  return JSON.stringify(roles);
}

// sharedRoles returns the role set common to EVERY operation page reachable
// under `node`, or null if they don't all share exactly one set — a Folder
// with no reachable pages is null (an empty section badged would be actively
// wrong), a bare Separator is always null, and a folder mixing role sets (or
// role-gated with ungated) is null so it gets no folder badge and its
// children are badged individually instead. This is the single derivation
// FOLDER/SEPARATOR badging uses — computed structurally, not a second flag
// that could drift from what the items say.
function sharedRoles(node: PageTreeNode, rolesByUrl: Map<string, string[]>): string[] | null {
  if (node.type === 'page') return rolesByUrl.get(node.url) ?? null;
  if (node.type === 'separator') return null;
  const leaves = node.index ? [node.index, ...node.children] : node.children;
  if (leaves.length === 0) return null;
  const first = sharedRoles(leaves[0], rolesByUrl);
  if (first === null) return null;
  const key = rolesKey(first);
  for (let i = 1; i < leaves.length; i++) {
    const roles = sharedRoles(leaves[i], rolesByUrl);
    if (roles === null || rolesKey(roles) !== key) return null;
  }
  return first;
}

// decorateChildren applies item-level badges to `children`, but ONLY when
// `containerRoles` is null — when the immediate container (the folder these
// children sit directly under) is itself getting a folder-level badge,
// badging every child too would be redundant clutter for no extra signal
// (see the 6 item-badge cases living in otherwise-mixed sections like Logs &
// Request Traces, vs. the ~40 operations under Platform (Admin) that get
// exactly one badge, on the section, not one each). A child that is itself a
// folder (only "git"'s two children today) is decorated with its OWN freshly
// computed set, recursing independently — a section can be mixed overall
// while one of its own sub-folders is uniform, or vice versa, and each
// level's badge has to reflect only that level's children.
function decorateChildren(children: PageTreeNode[], containerRoles: string[] | null, rolesByUrl: Map<string, string[]>): PageTreeNode[] {
  return children.map((child) => {
    if (child.type === 'folder') {
      const roles = sharedRoles(child, rolesByUrl);
      return { ...child, name: decorate(child.name, roles), children: decorateChildren(child.children, roles, rolesByUrl) };
    }
    if (child.type === 'page' && !containerRoles && rolesByUrl.has(child.url)) {
      return { ...child, name: decorate(child.name, rolesByUrl.get(child.url) ?? null) };
    }
    return child;
  });
}

// Render each SECTION folder (Server, Project, Application, Database under Core;
// live-updates, account, git, … under API) as a non-collapsible separator
// group — like the "Overview" group — instead of a collapsible folder. Only
// the sidebar tree changes: the pages keep their own nested URLs
// (`/docs/core/server/git`, …), so routing is unaffected. Doubly-nested
// folders (e.g. Application → Frameworks, or API's git → integrations/
// providers) stay collapsible — this only flattens one level.
//
// role badging rides along here rather than as a separate pass: badge status
// has to be computed BEFORE a folder collapses into a separator (a bare
// Separator has no `.children` left to inspect), so it has to happen at the
// same point flattening decides a node is a section in the first place.
function flattenSections(nodes: PageTreeNode[], rolesByUrl: Map<string, string[]>): PageTreeNode[] {
  const out: PageTreeNode[] = [];
  for (const node of nodes) {
    if (node.type === 'folder') {
      const roles = sharedRoles(node, rolesByUrl);
      out.push({ type: 'separator', name: decorate(node.name, roles) });
      if (node.index) out.push(...decorateChildren([node.index], roles, rolesByUrl));
      out.push(...decorateChildren(node.children, roles, rolesByUrl));
    } else {
      out.push(node);
    }
  }
  return out;
}

// Two `root: true` folders (Core, API — meta.json's "root" flag) exist so
// DocsLayout can render them as sidebar tabs (see `tabs` in layout.tsx): a
// root folder must stay a folder node, intact, for `getLayoutTabs()` to find
// it and for DocsLayout to scope the sidebar to whichever one is active. The
// flattening above therefore can't run at the top level like it used to when
// there was only one section total — it has to run INSIDE each root's own
// children instead, so "Server"/"Project"/etc. still render as flat groups
// once you're inside the Core tab, rather than as a nested collapsible folder.
export function getSidebarTree(): PageTreeRoot {
  const tree = source.getPageTree();
  const children: PageTreeNode[] = [];

  // Page tree nodes carry no `security` field — building this map from
  // source.getPages() (public API, not the tree's own @internal $ref) is
  // the one place role gating is read off page data, then threaded through
  // flattenSections/decorateChildren by URL rather than re-derived per node.
  const rolesByUrl = new Map<string, string[]>();
  for (const page of source.getPages()) {
    const roles = page.data.roles;
    if (Array.isArray(roles) && roles.length > 0) rolesByUrl.set(page.url, roles);
  }

  for (const node of tree.children) {
    if (node.type === 'folder' && node.root) {
      children.push({ ...node, children: flattenSections(node.children, rolesByUrl) });
    } else if (node.type === 'folder') {
      children.push(...flattenSections([node], rolesByUrl));
    } else {
      children.push(node);
    }
  }

  return { ...tree, children };
}

export function getPageImage(page: (typeof source)['$inferPage']) {
  const segments = [...page.slugs, 'image.png'];

  return {
    segments,
    url: `${docsImageRoute}/${segments.join('/')}`,
  };
}

export function getPageMarkdownUrl(page: (typeof source)['$inferPage']) {
  const segments = [...page.slugs, 'content.md'];

  return {
    segments,
    url: `${docsContentRoute}/${segments.join('/')}`,
  };
}

export async function getLLMText(page: (typeof source)['$inferPage']) {
  const processed = await page.data.getText('processed');

  return `# ${page.data.title} (${page.url})

${processed}`;
}
