/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppSettingsServerRouteImport } from './routes/_app/settings/server'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app/projects/$projectId/settings'
import { Route as AppProjectsProjectIdServicesServiceIdRouteImport } from './routes/_app/projects/$projectId/services/$serviceId'
import { Route as AppProjectsProjectIdDatabasesDatabaseIdRouteImport } from './routes/_app/projects/$projectId/databases/$databaseId'
import { Route as AppProjectsProjectIdServicesServiceIdIndexRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/index'
import { Route as AppProjectsProjectIdServicesServiceIdSettingsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/settings'
import { Route as AppProjectsProjectIdServicesServiceIdLogsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/logs'
import { Route as AppProjectsProjectIdServicesServiceIdEnvRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/env'
import { Route as AppProjectsProjectIdServicesServiceIdDomainsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/domains'
import { Route as AppProjectsProjectIdServicesServiceIdDeploymentsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/deployments'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsServerRoute = AppSettingsServerRouteImport.update({
  id: '/settings/server',
  path: '/settings/server',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdRoute =
  AppProjectsProjectIdServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDatabasesDatabaseIdRoute =
  AppProjectsProjectIdDatabasesDatabaseIdRouteImport.update({
    id: '/databases/$databaseId',
    path: '/databases/$databaseId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdIndexRoute =
  AppProjectsProjectIdServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdSettingsRoute =
  AppProjectsProjectIdServicesServiceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdLogsRoute =
  AppProjectsProjectIdServicesServiceIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdEnvRoute =
  AppProjectsProjectIdServicesServiceIdEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdDomainsRoute =
  AppProjectsProjectIdServicesServiceIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdDeploymentsRoute =
  AppProjectsProjectIdServicesServiceIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/settings/server': typeof AppSettingsServerRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/databases/$databaseId': typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  '/projects/$projectId/services/$serviceId': typeof AppProjectsProjectIdServicesServiceIdRouteWithChildren
  '/projects/$projectId/services/$serviceId/deployments': typeof AppProjectsProjectIdServicesServiceIdDeploymentsRoute
  '/projects/$projectId/services/$serviceId/domains': typeof AppProjectsProjectIdServicesServiceIdDomainsRoute
  '/projects/$projectId/services/$serviceId/env': typeof AppProjectsProjectIdServicesServiceIdEnvRoute
  '/projects/$projectId/services/$serviceId/logs': typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  '/projects/$projectId/services/$serviceId/settings': typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  '/projects/$projectId/services/$serviceId/': typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/settings/server': typeof AppSettingsServerRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/databases/$databaseId': typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  '/projects/$projectId/services/$serviceId/deployments': typeof AppProjectsProjectIdServicesServiceIdDeploymentsRoute
  '/projects/$projectId/services/$serviceId/domains': typeof AppProjectsProjectIdServicesServiceIdDomainsRoute
  '/projects/$projectId/services/$serviceId/env': typeof AppProjectsProjectIdServicesServiceIdEnvRoute
  '/projects/$projectId/services/$serviceId/logs': typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  '/projects/$projectId/services/$serviceId/settings': typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  '/projects/$projectId/services/$serviceId': typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/settings/server': typeof AppSettingsServerRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/databases/$databaseId': typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  '/_app/projects/$projectId/services/$serviceId': typeof AppProjectsProjectIdServicesServiceIdRouteWithChildren
  '/_app/projects/$projectId/services/$serviceId/deployments': typeof AppProjectsProjectIdServicesServiceIdDeploymentsRoute
  '/_app/projects/$projectId/services/$serviceId/domains': typeof AppProjectsProjectIdServicesServiceIdDomainsRoute
  '/_app/projects/$projectId/services/$serviceId/env': typeof AppProjectsProjectIdServicesServiceIdEnvRoute
  '/_app/projects/$projectId/services/$serviceId/logs': typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  '/_app/projects/$projectId/services/$serviceId/settings': typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  '/_app/projects/$projectId/services/$serviceId/': typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/dashboard'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/server'
    | '/settings/team'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/databases/$databaseId'
    | '/projects/$projectId/services/$serviceId'
    | '/projects/$projectId/services/$serviceId/deployments'
    | '/projects/$projectId/services/$serviceId/domains'
    | '/projects/$projectId/services/$serviceId/env'
    | '/projects/$projectId/services/$serviceId/logs'
    | '/projects/$projectId/services/$serviceId/settings'
    | '/projects/$projectId/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/dashboard'
    | '/projects/new'
    | '/settings/server'
    | '/settings/team'
    | '/projects'
    | '/settings'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/databases/$databaseId'
    | '/projects/$projectId/services/$serviceId/deployments'
    | '/projects/$projectId/services/$serviceId/domains'
    | '/projects/$projectId/services/$serviceId/env'
    | '/projects/$projectId/services/$serviceId/logs'
    | '/projects/$projectId/services/$serviceId/settings'
    | '/projects/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/dashboard'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/settings/server'
    | '/_app/settings/team'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/databases/$databaseId'
    | '/_app/projects/$projectId/services/$serviceId'
    | '/_app/projects/$projectId/services/$serviceId/deployments'
    | '/_app/projects/$projectId/services/$serviceId/domains'
    | '/_app/projects/$projectId/services/$serviceId/env'
    | '/_app/projects/$projectId/services/$serviceId/logs'
    | '/_app/projects/$projectId/services/$serviceId/settings'
    | '/_app/projects/$projectId/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/server': {
      id: '/_app/settings/server'
      path: '/settings/server'
      fullPath: '/settings/server'
      preLoaderRoute: typeof AppSettingsServerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId': {
      id: '/_app/projects/$projectId/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/databases/$databaseId': {
      id: '/_app/projects/$projectId/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/projects/$projectId/databases/$databaseId'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDatabaseIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/': {
      id: '/_app/projects/$projectId/services/$serviceId/'
      path: '/'
      fullPath: '/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/settings': {
      id: '/_app/projects/$projectId/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/services/$serviceId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/logs': {
      id: '/_app/projects/$projectId/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/services/$serviceId/logs'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/env': {
      id: '/_app/projects/$projectId/services/$serviceId/env'
      path: '/env'
      fullPath: '/projects/$projectId/services/$serviceId/env'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdEnvRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/domains': {
      id: '/_app/projects/$projectId/services/$serviceId/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/services/$serviceId/domains'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdDomainsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/deployments': {
      id: '/_app/projects/$projectId/services/$serviceId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/services/$serviceId/deployments'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdDeploymentsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
  }
}

interface AppProjectsProjectIdServicesServiceIdRouteChildren {
  AppProjectsProjectIdServicesServiceIdDeploymentsRoute: typeof AppProjectsProjectIdServicesServiceIdDeploymentsRoute
  AppProjectsProjectIdServicesServiceIdDomainsRoute: typeof AppProjectsProjectIdServicesServiceIdDomainsRoute
  AppProjectsProjectIdServicesServiceIdEnvRoute: typeof AppProjectsProjectIdServicesServiceIdEnvRoute
  AppProjectsProjectIdServicesServiceIdLogsRoute: typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  AppProjectsProjectIdServicesServiceIdSettingsRoute: typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  AppProjectsProjectIdServicesServiceIdIndexRoute: typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}

const AppProjectsProjectIdServicesServiceIdRouteChildren: AppProjectsProjectIdServicesServiceIdRouteChildren =
  {
    AppProjectsProjectIdServicesServiceIdDeploymentsRoute:
      AppProjectsProjectIdServicesServiceIdDeploymentsRoute,
    AppProjectsProjectIdServicesServiceIdDomainsRoute:
      AppProjectsProjectIdServicesServiceIdDomainsRoute,
    AppProjectsProjectIdServicesServiceIdEnvRoute:
      AppProjectsProjectIdServicesServiceIdEnvRoute,
    AppProjectsProjectIdServicesServiceIdLogsRoute:
      AppProjectsProjectIdServicesServiceIdLogsRoute,
    AppProjectsProjectIdServicesServiceIdSettingsRoute:
      AppProjectsProjectIdServicesServiceIdSettingsRoute,
    AppProjectsProjectIdServicesServiceIdIndexRoute:
      AppProjectsProjectIdServicesServiceIdIndexRoute,
  }

const AppProjectsProjectIdServicesServiceIdRouteWithChildren =
  AppProjectsProjectIdServicesServiceIdRoute._addFileChildren(
    AppProjectsProjectIdServicesServiceIdRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdDatabasesDatabaseIdRoute: typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  AppProjectsProjectIdServicesServiceIdRoute: typeof AppProjectsProjectIdServicesServiceIdRouteWithChildren
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdDatabasesDatabaseIdRoute:
    AppProjectsProjectIdDatabasesDatabaseIdRoute,
  AppProjectsProjectIdServicesServiceIdRoute:
    AppProjectsProjectIdServicesServiceIdRouteWithChildren,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppSettingsServerRoute: typeof AppSettingsServerRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppSettingsServerRoute: AppSettingsServerRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
