/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppDeploymentsIndexRouteImport } from './routes/_app/deployments/index'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppSettingsServerRouteImport } from './routes/_app/settings/server'
import { Route as AppSettingsGitCredentialsRouteImport } from './routes/_app/settings/git-credentials'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app/projects/$projectId/settings'
import { Route as AppProjectsProjectIdEnvRouteImport } from './routes/_app/projects/$projectId/env'
import { Route as AppProjectsProjectIdDatabasesDatabaseIdRouteImport } from './routes/_app/projects/$projectId/databases/$databaseId'
import { Route as AppProjectsProjectIdApplicationsApplicationIdRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId'
import { Route as AppProjectsProjectIdApplicationsApplicationIdIndexRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/index'
import { Route as AppProjectsProjectIdApplicationsApplicationIdSettingsRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/settings'
import { Route as AppProjectsProjectIdApplicationsApplicationIdMetricsRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/metrics'
import { Route as AppProjectsProjectIdApplicationsApplicationIdLogsRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/logs'
import { Route as AppProjectsProjectIdApplicationsApplicationIdEnvRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/env'
import { Route as AppProjectsProjectIdApplicationsApplicationIdDomainsRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/domains'
import { Route as AppProjectsProjectIdApplicationsApplicationIdDeploymentsRouteImport } from './routes/_app/projects/$projectId/applications/$applicationId/deployments'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsIndexRoute = AppDeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsServerRoute = AppSettingsServerRouteImport.update({
  id: '/settings/server',
  path: '/settings/server',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGitCredentialsRoute =
  AppSettingsGitCredentialsRouteImport.update({
    id: '/settings/git-credentials',
    path: '/settings/git-credentials',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdEnvRoute = AppProjectsProjectIdEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AppProjectsProjectIdRoute,
} as any)
const AppProjectsProjectIdDatabasesDatabaseIdRoute =
  AppProjectsProjectIdDatabasesDatabaseIdRouteImport.update({
    id: '/databases/$databaseId',
    path: '/databases/$databaseId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdRoute =
  AppProjectsProjectIdApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdIndexRoute =
  AppProjectsProjectIdApplicationsApplicationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdSettingsRoute =
  AppProjectsProjectIdApplicationsApplicationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdMetricsRoute =
  AppProjectsProjectIdApplicationsApplicationIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdLogsRoute =
  AppProjectsProjectIdApplicationsApplicationIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdEnvRoute =
  AppProjectsProjectIdApplicationsApplicationIdEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdDomainsRoute =
  AppProjectsProjectIdApplicationsApplicationIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute =
  AppProjectsProjectIdApplicationsApplicationIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppProjectsProjectIdApplicationsApplicationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/git-credentials': typeof AppSettingsGitCredentialsRoute
  '/settings/server': typeof AppSettingsServerRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/deployments/': typeof AppDeploymentsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/projects/$projectId/env': typeof AppProjectsProjectIdEnvRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$applicationId': typeof AppProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  '/projects/$projectId/databases/$databaseId': typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  '/projects/$projectId/applications/$applicationId/deployments': typeof AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute
  '/projects/$projectId/applications/$applicationId/domains': typeof AppProjectsProjectIdApplicationsApplicationIdDomainsRoute
  '/projects/$projectId/applications/$applicationId/env': typeof AppProjectsProjectIdApplicationsApplicationIdEnvRoute
  '/projects/$projectId/applications/$applicationId/logs': typeof AppProjectsProjectIdApplicationsApplicationIdLogsRoute
  '/projects/$projectId/applications/$applicationId/metrics': typeof AppProjectsProjectIdApplicationsApplicationIdMetricsRoute
  '/projects/$projectId/applications/$applicationId/settings': typeof AppProjectsProjectIdApplicationsApplicationIdSettingsRoute
  '/projects/$projectId/applications/$applicationId/': typeof AppProjectsProjectIdApplicationsApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/git-credentials': typeof AppSettingsGitCredentialsRoute
  '/settings/server': typeof AppSettingsServerRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/deployments': typeof AppDeploymentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/requests': typeof AppRequestsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$projectId/env': typeof AppProjectsProjectIdEnvRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/databases/$databaseId': typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  '/projects/$projectId/applications/$applicationId/deployments': typeof AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute
  '/projects/$projectId/applications/$applicationId/domains': typeof AppProjectsProjectIdApplicationsApplicationIdDomainsRoute
  '/projects/$projectId/applications/$applicationId/env': typeof AppProjectsProjectIdApplicationsApplicationIdEnvRoute
  '/projects/$projectId/applications/$applicationId/logs': typeof AppProjectsProjectIdApplicationsApplicationIdLogsRoute
  '/projects/$projectId/applications/$applicationId/metrics': typeof AppProjectsProjectIdApplicationsApplicationIdMetricsRoute
  '/projects/$projectId/applications/$applicationId/settings': typeof AppProjectsProjectIdApplicationsApplicationIdSettingsRoute
  '/projects/$projectId/applications/$applicationId': typeof AppProjectsProjectIdApplicationsApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/git-credentials': typeof AppSettingsGitCredentialsRoute
  '/_app/settings/server': typeof AppSettingsServerRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/deployments/': typeof AppDeploymentsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/projects/$projectId/env': typeof AppProjectsProjectIdEnvRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/applications/$applicationId': typeof AppProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  '/_app/projects/$projectId/databases/$databaseId': typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
  '/_app/projects/$projectId/applications/$applicationId/deployments': typeof AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute
  '/_app/projects/$projectId/applications/$applicationId/domains': typeof AppProjectsProjectIdApplicationsApplicationIdDomainsRoute
  '/_app/projects/$projectId/applications/$applicationId/env': typeof AppProjectsProjectIdApplicationsApplicationIdEnvRoute
  '/_app/projects/$projectId/applications/$applicationId/logs': typeof AppProjectsProjectIdApplicationsApplicationIdLogsRoute
  '/_app/projects/$projectId/applications/$applicationId/metrics': typeof AppProjectsProjectIdApplicationsApplicationIdMetricsRoute
  '/_app/projects/$projectId/applications/$applicationId/settings': typeof AppProjectsProjectIdApplicationsApplicationIdSettingsRoute
  '/_app/projects/$projectId/applications/$applicationId/': typeof AppProjectsProjectIdApplicationsApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/dashboard'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/audit'
    | '/settings/git-credentials'
    | '/settings/server'
    | '/settings/team'
    | '/deployments/'
    | '/projects/'
    | '/requests/'
    | '/settings/'
    | '/projects/$projectId/env'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/applications/$applicationId'
    | '/projects/$projectId/databases/$databaseId'
    | '/projects/$projectId/applications/$applicationId/deployments'
    | '/projects/$projectId/applications/$applicationId/domains'
    | '/projects/$projectId/applications/$applicationId/env'
    | '/projects/$projectId/applications/$applicationId/logs'
    | '/projects/$projectId/applications/$applicationId/metrics'
    | '/projects/$projectId/applications/$applicationId/settings'
    | '/projects/$projectId/applications/$applicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/dashboard'
    | '/projects/new'
    | '/settings/audit'
    | '/settings/git-credentials'
    | '/settings/server'
    | '/settings/team'
    | '/deployments'
    | '/projects'
    | '/requests'
    | '/settings'
    | '/projects/$projectId/env'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/databases/$databaseId'
    | '/projects/$projectId/applications/$applicationId/deployments'
    | '/projects/$projectId/applications/$applicationId/domains'
    | '/projects/$projectId/applications/$applicationId/env'
    | '/projects/$projectId/applications/$applicationId/logs'
    | '/projects/$projectId/applications/$applicationId/metrics'
    | '/projects/$projectId/applications/$applicationId/settings'
    | '/projects/$projectId/applications/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/dashboard'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/settings/audit'
    | '/_app/settings/git-credentials'
    | '/_app/settings/server'
    | '/_app/settings/team'
    | '/_app/deployments/'
    | '/_app/projects/'
    | '/_app/requests/'
    | '/_app/settings/'
    | '/_app/projects/$projectId/env'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/applications/$applicationId'
    | '/_app/projects/$projectId/databases/$databaseId'
    | '/_app/projects/$projectId/applications/$applicationId/deployments'
    | '/_app/projects/$projectId/applications/$applicationId/domains'
    | '/_app/projects/$projectId/applications/$applicationId/env'
    | '/_app/projects/$projectId/applications/$applicationId/logs'
    | '/_app/projects/$projectId/applications/$applicationId/metrics'
    | '/_app/projects/$projectId/applications/$applicationId/settings'
    | '/_app/projects/$projectId/applications/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments/': {
      id: '/_app/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof AppDeploymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/server': {
      id: '/_app/settings/server'
      path: '/settings/server'
      fullPath: '/settings/server'
      preLoaderRoute: typeof AppSettingsServerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/git-credentials': {
      id: '/_app/settings/git-credentials'
      path: '/settings/git-credentials'
      fullPath: '/settings/git-credentials'
      preLoaderRoute: typeof AppSettingsGitCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/env': {
      id: '/_app/projects/$projectId/env'
      path: '/env'
      fullPath: '/projects/$projectId/env'
      preLoaderRoute: typeof AppProjectsProjectIdEnvRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/databases/$databaseId': {
      id: '/_app/projects/$projectId/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/projects/$projectId/databases/$databaseId'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDatabaseIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId': {
      id: '/_app/projects/$projectId/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/projects/$projectId/applications/$applicationId'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/': {
      id: '/_app/projects/$projectId/applications/$applicationId/'
      path: '/'
      fullPath: '/projects/$projectId/applications/$applicationId/'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/settings': {
      id: '/_app/projects/$projectId/applications/$applicationId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/applications/$applicationId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/metrics': {
      id: '/_app/projects/$projectId/applications/$applicationId/metrics'
      path: '/metrics'
      fullPath: '/projects/$projectId/applications/$applicationId/metrics'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdMetricsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/logs': {
      id: '/_app/projects/$projectId/applications/$applicationId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/applications/$applicationId/logs'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/env': {
      id: '/_app/projects/$projectId/applications/$applicationId/env'
      path: '/env'
      fullPath: '/projects/$projectId/applications/$applicationId/env'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdEnvRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/domains': {
      id: '/_app/projects/$projectId/applications/$applicationId/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/applications/$applicationId/domains'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdDomainsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
    '/_app/projects/$projectId/applications/$applicationId/deployments': {
      id: '/_app/projects/$projectId/applications/$applicationId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/applications/$applicationId/deployments'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsApplicationIdDeploymentsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRoute
    }
  }
}

interface AppProjectsProjectIdApplicationsApplicationIdRouteChildren {
  AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute: typeof AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute
  AppProjectsProjectIdApplicationsApplicationIdDomainsRoute: typeof AppProjectsProjectIdApplicationsApplicationIdDomainsRoute
  AppProjectsProjectIdApplicationsApplicationIdEnvRoute: typeof AppProjectsProjectIdApplicationsApplicationIdEnvRoute
  AppProjectsProjectIdApplicationsApplicationIdLogsRoute: typeof AppProjectsProjectIdApplicationsApplicationIdLogsRoute
  AppProjectsProjectIdApplicationsApplicationIdMetricsRoute: typeof AppProjectsProjectIdApplicationsApplicationIdMetricsRoute
  AppProjectsProjectIdApplicationsApplicationIdSettingsRoute: typeof AppProjectsProjectIdApplicationsApplicationIdSettingsRoute
  AppProjectsProjectIdApplicationsApplicationIdIndexRoute: typeof AppProjectsProjectIdApplicationsApplicationIdIndexRoute
}

const AppProjectsProjectIdApplicationsApplicationIdRouteChildren: AppProjectsProjectIdApplicationsApplicationIdRouteChildren =
  {
    AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute:
      AppProjectsProjectIdApplicationsApplicationIdDeploymentsRoute,
    AppProjectsProjectIdApplicationsApplicationIdDomainsRoute:
      AppProjectsProjectIdApplicationsApplicationIdDomainsRoute,
    AppProjectsProjectIdApplicationsApplicationIdEnvRoute:
      AppProjectsProjectIdApplicationsApplicationIdEnvRoute,
    AppProjectsProjectIdApplicationsApplicationIdLogsRoute:
      AppProjectsProjectIdApplicationsApplicationIdLogsRoute,
    AppProjectsProjectIdApplicationsApplicationIdMetricsRoute:
      AppProjectsProjectIdApplicationsApplicationIdMetricsRoute,
    AppProjectsProjectIdApplicationsApplicationIdSettingsRoute:
      AppProjectsProjectIdApplicationsApplicationIdSettingsRoute,
    AppProjectsProjectIdApplicationsApplicationIdIndexRoute:
      AppProjectsProjectIdApplicationsApplicationIdIndexRoute,
  }

const AppProjectsProjectIdApplicationsApplicationIdRouteWithChildren =
  AppProjectsProjectIdApplicationsApplicationIdRoute._addFileChildren(
    AppProjectsProjectIdApplicationsApplicationIdRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdEnvRoute: typeof AppProjectsProjectIdEnvRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdApplicationsApplicationIdRoute: typeof AppProjectsProjectIdApplicationsApplicationIdRouteWithChildren
  AppProjectsProjectIdDatabasesDatabaseIdRoute: typeof AppProjectsProjectIdDatabasesDatabaseIdRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdEnvRoute: AppProjectsProjectIdEnvRoute,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdApplicationsApplicationIdRoute:
    AppProjectsProjectIdApplicationsApplicationIdRouteWithChildren,
  AppProjectsProjectIdDatabasesDatabaseIdRoute:
    AppProjectsProjectIdDatabasesDatabaseIdRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsGitCredentialsRoute: typeof AppSettingsGitCredentialsRoute
  AppSettingsServerRoute: typeof AppSettingsServerRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppDeploymentsIndexRoute: typeof AppDeploymentsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsGitCredentialsRoute: AppSettingsGitCredentialsRoute,
  AppSettingsServerRoute: AppSettingsServerRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppDeploymentsIndexRoute: AppDeploymentsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
